image:
  repository: "${DOCKERHUB_USERNAME}/db4fresh"
  pullPolicy: IfNotPresent
  tag: "latest"

backend:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5000

frontend:
  replicaCount: 1
  service:
    type: LoadBalancer
    port: 80
